connections {
    vm1-vm2 {
        version = 2
        local_addrs  = 10.0.2.5
        remote_addrs = 10.0.2.6

        proposals = aes256gcm16-prfsha384-mlkem768

        local {
            auth = pubkey
            certs = vm1Cert.pem
            id = vm1
        }
        remote {
            auth = pubkey
            id = vm2
        }
        children {
            host-host {
                local_ts  = 10.0.2.5/32
                remote_ts = 10.0.2.6/32
                esp_proposals = aes256gcm16-mlkem768
                start_action = trap
            }
        }
    }
}
